/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneotomasyonu.uye;

import kutuphaneotomasyonu.siniflar.Uye;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import kutuphaneotomasyonu.SqlBaglantisi;
import static kutuphaneotomasyonu.uye.Üyeler.uyeListesi;

/**
 *
 * @author fxd
 */
public class ÜyeEkle extends javax.swing.JFrame {

    /**
     * Creates new form ÜyeEkle
     */
    SqlBaglantisi baglanti = new SqlBaglantisi();

    public ÜyeEkle() {
        initComponents();
        try {
            uyeListesi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    try {
                        baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
                        int row = uyeListesi.getSelectedRow();
                        String tableClick = (uyeListesi.getModel().getValueAt(row, 0).toString());

                        String sql = "select * from uyeler where id='" + tableClick + "'";

                        SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement(sql);
                        SqlBaglantisi.rs = SqlBaglantisi.prs.executeQuery();

                        if (SqlBaglantisi.rs.next()) {
                            tcTextBox.setText(SqlBaglantisi.rs.getString("tc"));
                            adTextBox.setText(SqlBaglantisi.rs.getString("adi"));
                            soyadTextBox.setText(SqlBaglantisi.rs.getString("soyadi"));
                            telefonTextBox.setText(SqlBaglantisi.rs.getString("telefon_no"));
                            adresTextBox.setText(SqlBaglantisi.rs.getString("adres"));
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Üye Listesi Yüklenemedi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tcTextBox = new javax.swing.JTextField();
        uyeEkleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        telefonTextBox = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        adTextBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        soyadTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adresTextBox = new javax.swing.JTextArea();
        güncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Üye Kaydı");

        tcTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcTextBoxKeyTyped(evt);
            }
        });

        uyeEkleButton.setText("Üye Ekle");
        uyeEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeEkleButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("TC");

        try {
            telefonTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0###)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Ad");

        adTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adTextBoxKeyTyped(evt);
            }
        });

        jLabel3.setText("Soyad");

        soyadTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soyadTextBoxKeyTyped(evt);
            }
        });

        jLabel4.setText("Telefon");

        jLabel5.setText("Adres");

        adresTextBox.setColumns(20);
        adresTextBox.setRows(5);
        adresTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adresTextBoxKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(adresTextBox);

        güncelleButton.setText("Güncelle");
        güncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(46, 46, 46)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(43, 43, 43))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(34, 34, 34)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tcTextBox)
                                .addComponent(adTextBox)
                                .addComponent(soyadTextBox)
                                .addComponent(telefonTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(güncelleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uyeEkleButton)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uyeEkleButton)
                            .addComponent(güncelleButton)))
                    .addComponent(telefonTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uyeEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeEkleButtonActionPerformed

        try {
            if (tcTextBox.getText().length() < 11)
                JOptionPane.showMessageDialog(null, "TC Kimlik Numarasını Eksik Girdiniz");
            else if(telefonTextBox.getText().length()<11)
                     JOptionPane.showMessageDialog(null, "Telefon Numarasını Eksik Girdiniz");
            else if(telefonTextBox.getText().equals("") || tcTextBox.getText().equals("") || adTextBox.getText().equals("") || soyadTextBox.getText().equals("") || adresTextBox.getText().equals(""))
                    JOptionPane.showMessageDialog(null, "Eksik Bilgi Girdiniz","Eksik Bilgi Girdiniz",HEIGHT);
                else {
                Uye uye = new Uye();
                baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
                SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("insert into uyeler(tc,adi,soyadi,telefon_no,adres) values(?,?,?,?,?)");

                uye.setAdi(adTextBox.getText());
                uye.setAdres(adresTextBox.getText());
                uye.setSoyadi(soyadTextBox.getText());
                uye.setTc(tcTextBox.getText());
                uye.setTelefon(telefonTextBox.getText());

                SqlBaglantisi.prs.setString(1, uye.getTc());
                SqlBaglantisi.prs.setString(2, uye.getAdi());
                SqlBaglantisi.prs.setString(3, uye.getSoyadi());
                SqlBaglantisi.prs.setString(4, uye.getTelefon());
                SqlBaglantisi.prs.setString(5, uye.getAdres());

                SqlBaglantisi.prs.executeUpdate();

                JOptionPane.showMessageDialog(null, "Uye eklendi");
                tcTextBox.setText("");
                adTextBox.setText("");
                soyadTextBox.setText("");
                telefonTextBox.setText("");
                adresTextBox.setText("");
                Üyeler.UyeTablo();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ÜyeEkle.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Üye eklenirken hata oluştu lütfen bilgileri kontrol edin","Üye eklenirken hata oluştu lütfen bilgileri kontrol edin",HEIGHT);
        }
        finally
        {
            try {
                SqlBaglantisi.con.close();
                SqlBaglantisi.prs.close();
                SqlBaglantisi.rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Üyeler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_uyeEkleButtonActionPerformed
    //Tuş yazılmış ise çalışacak koddur.KeyTyped tuş yazılmışsa olacak olan olaylar içindir.
    private void tcTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcTextBoxKeyTyped
        //tc nin uzunluğu 11den fazla ise olayı durdurdum.
        if (tcTextBox.getText().length() >= 11)
            evt.consume();
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_tcTextBoxKeyTyped

    private void adresTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresTextBoxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER)
            uyeEkleButton.requestFocus();
    }//GEN-LAST:event_adresTextBoxKeyTyped

    private void adTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adTextBoxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || adTextBox.getText().length() == 15) 
            evt.consume();
        if (adTextBox.getText().length() == 1) 
            adTextBox.setText(adTextBox.getText().toUpperCase());
    }//GEN-LAST:event_adTextBoxKeyTyped

    private void soyadTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soyadTextBoxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || adTextBox.getText().length() == 15) 
            evt.consume();
        if (soyadTextBox.getText().length() == 1) 
            soyadTextBox.setText(soyadTextBox.getText().toUpperCase());
    }//GEN-LAST:event_soyadTextBoxKeyTyped

    private void güncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButtonActionPerformed
        SqlBaglantisi baglanti = new SqlBaglantisi();
        try {
            baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
            SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("update uyeler set tc='" + tcTextBox.getText() + "',adi='" + adTextBox.getText() 
                    + "',soyadi='" + soyadTextBox.getText() + "',telefon_no='"+telefonTextBox.getText()+"',adres='"+adresTextBox.getText()+"' "
                    + "where tc='" + tcTextBox.getText() + "' ");
            JOptionPane.showMessageDialog(null, "Üye Güncellendi","Üye Güncellendi",WIDTH);
            SqlBaglantisi.prs.executeUpdate();

            Üyeler.UyeTablo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Üye Güncellenemedi","Üye Güncellenemedi",HEIGHT);
        }
        finally
        {
            try {
                SqlBaglantisi.con.close();
                SqlBaglantisi.prs.close();
                SqlBaglantisi.rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Üyeler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_güncelleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÜyeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÜyeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÜyeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÜyeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÜyeEkle().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTextBox;
    private javax.swing.JTextArea adresTextBox;
    private javax.swing.JButton güncelleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField soyadTextBox;
    private javax.swing.JTextField tcTextBox;
    private javax.swing.JFormattedTextField telefonTextBox;
    private javax.swing.JButton uyeEkleButton;
    // End of variables declaration//GEN-END:variables
}
