/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneotomasyonu.personel;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import kutuphaneotomasyonu.SqlBaglantisi;
import kutuphaneotomasyonu.siniflar.Personel;
import kutuphaneotomasyonu.uye.ÜyeEkle;
import kutuphaneotomasyonu.uye.Üyeler;
/**
 *
 * @author fxd
 */
public class PersonelEkle extends javax.swing.JFrame {

    /**
     * Creates new form PersonelEkle
     */
    static int id=0;
    public PersonelEkle() {
        initComponents();
        try {
                
                Personeller.personeListesi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    try {
                        SqlBaglantisi baglanti=new SqlBaglantisi();
                        baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
                        int row = Personeller.personeListesi.getSelectedRow();
                        String tableClick = (Personeller.personeListesi.getModel().getValueAt(row, 0).toString());

                        String sql = "select * from personel where id='" + tableClick + "'";

                        SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement(sql);
                        SqlBaglantisi.rs = SqlBaglantisi.prs.executeQuery();

                        if (SqlBaglantisi.rs.next()) {
                            personelAdi.setText(SqlBaglantisi.rs.getString("adi"));
                            personelSoyadi.setText(SqlBaglantisi.rs.getString("soyadi"));
                            personelNo.setText(SqlBaglantisi.rs.getString("personel_no").substring(3));
                            id=SqlBaglantisi.rs.getInt("id");
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Personel Listesi Yüklenemedi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eklePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        personelAdi = new javax.swing.JTextField();
        personelSoyadi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        personelNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kaydetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        güncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eklePanel.setBackground(new java.awt.Color(255, 255, 255));
        eklePanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ad");

        personelAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personelAdiKeyTyped(evt);
            }
        });

        personelSoyadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personelSoyadiKeyTyped(evt);
            }
        });

        jLabel2.setText("Soyad");

        personelNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personelNoKeyTyped(evt);
            }
        });

        jLabel3.setText("Personel No");

        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("100");

        güncelleButton.setText("Güncelle");
        güncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eklePanelLayout = new javax.swing.GroupLayout(eklePanel);
        eklePanel.setLayout(eklePanelLayout);
        eklePanelLayout.setHorizontalGroup(
            eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eklePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eklePanelLayout.createSequentialGroup()
                        .addComponent(güncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kaydetButton))
                    .addGroup(eklePanelLayout.createSequentialGroup()
                        .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eklePanelLayout.createSequentialGroup()
                                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(89, 89, 89))
                            .addGroup(eklePanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personelAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(personelSoyadi)
                            .addComponent(personelNo))
                        .addGap(7, 7, 7)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        eklePanelLayout.setVerticalGroup(
            eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eklePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(personelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personelSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(personelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydetButton)
                    .addComponent(güncelleButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
        // TODO add your handling code here:
        SqlBaglantisi baglanti = new SqlBaglantisi();

        try {
            if (personelNo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Lütfen Personel Numarasını Giriniz");
            } else {
                Personel personel = new Personel();
                String personelSifreString="100"+personelNo.getText()+"-"+personelAdi.getText().toLowerCase();
                baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
                SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("insert into personel(adi,soyadi,personel_no,personel_sifre) values(?,?,?,?)");

                personel.setAdi(personelAdi.getText());
                personel.setSoyadi(personelSoyadi.getText());
                String personelNoString="100"+this.personelNo.getText();
                personel.setPersonelNo(Integer.valueOf(personelNoString));
                personel.setPersoneSifre(personelSifreString);

                SqlBaglantisi.prs.setString(1, personel.getAdi());
                SqlBaglantisi.prs.setString(2, personel.getSoyadi());
                SqlBaglantisi.prs.setInt(3, personel.getPersonelNo());
                SqlBaglantisi.prs.setString(4, personel.getPersoneSifre());

                SqlBaglantisi.prs.executeUpdate();

                personelAdi.setText("");
                personelNo.setText("");
                personelSoyadi.setText("");
                JOptionPane.showMessageDialog(null, "Personel Eklendi");
                Personeller.PersonelTablo();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ÜyeEkle.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Personel Eklenemedi");
        }
        finally
        {
            try {
                SqlBaglantisi.con.close();
                SqlBaglantisi.prs.close();
                SqlBaglantisi.rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Üyeler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_kaydetButtonActionPerformed

    private void personelAdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personelAdiKeyTyped
        char c=evt.getKeyChar();
        if (Character.isDigit(c) || c==KeyEvent.VK_SPACE || personelAdi.getText().length()==15)
            evt.consume();
        if (personelAdi.getText().length()==1)
            personelAdi.setText(personelAdi.getText().toUpperCase());
    }//GEN-LAST:event_personelAdiKeyTyped

    private void personelSoyadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personelSoyadiKeyTyped
        char c=evt.getKeyChar();
        if (Character.isDigit(c) || c==KeyEvent.VK_SPACE || personelSoyadi.getText().length()==15)
            evt.consume();
        if (personelSoyadi.getText().length()==1)
            personelSoyadi.setText(personelSoyadi.getText().toUpperCase());
    }//GEN-LAST:event_personelSoyadiKeyTyped

    private void personelNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personelNoKeyTyped
        char c=evt.getKeyChar();
        if (Character.isAlphabetic(c) || c==KeyEvent.VK_SPACE || personelNo.getText().length()==10)
            evt.consume();
    }//GEN-LAST:event_personelNoKeyTyped

    private void güncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButtonActionPerformed
        // TODO add your handling code here:
        SqlBaglantisi baglanti = new SqlBaglantisi();
        try {
            baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
            SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("update personel set adi='"+personelAdi.getText()+"',soyadi='"+personelSoyadi.getText()+"',personel_no='"+"100"+personelNo.getText()+"' "
                    + "where id='"+id+"'");
            JOptionPane.showMessageDialog(null, "Personel Güncellendi");
            SqlBaglantisi.prs.executeUpdate();

            Personeller.PersonelTablo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Personel Güncellenemedi");
        }
        finally
        {
            try {
                SqlBaglantisi.con.close();
                SqlBaglantisi.prs.close();
                SqlBaglantisi.rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Üyeler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_güncelleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel eklePanel;
    private javax.swing.JButton güncelleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JTextField personelAdi;
    private javax.swing.JTextField personelNo;
    private javax.swing.JTextField personelSoyadi;
    // End of variables declaration//GEN-END:variables
}
