/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneotomasyonu;

import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kutuphaneotomasyonu.siniflar.Personel;

/**
 *
 * @author fxd
 */
public class GirisEkranı extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkranı
     */
    public GirisEkranı() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("src/Icons/lb.png");
        jLabel1.setIcon(icon);
        this.setTitle("Kütüphane Otomasyonu Giriş Ekranı");
        icon = new ImageIcon("src/Icons/library.png");
        this.setIconImage(icon.getImage());

    }
    Calendar c = Calendar.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kullaniciAdiTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        girisButton = new javax.swing.JButton();
        sifreTextBox = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(41, 128, 185));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        kullaniciAdiTextBox.setToolTipText("Kullanıcı Adı Personel Numaranızdır.");
        kullaniciAdiTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kullaniciAdiTextBoxKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Kullanıcı Adı");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Şifre");

        girisButton.setBackground(new java.awt.Color(255, 255, 255));
        girisButton.setForeground(new java.awt.Color(0, 0, 0));
        girisButton.setText("Giriş Yap");
        girisButton.setBorder(null);
        girisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButtonActionPerformed(evt);
            }
        });

        sifreTextBox.setToolTipText("Şifreniz Personel Numarası-Adınız(1000-fatih).");
        sifreTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sifreTextBoxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(girisButton, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(kullaniciAdiTextBox)
                    .addComponent(sifreTextBox))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kullaniciAdiTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sifreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(girisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void PersonelYazdir() throws IOException {
        File personelNumarasi = new File("personel_no.txt");
        if (personelNumarasi.exists()) {
            personelNumarasi.createNewFile();
        }
        FileWriter yazdir = new FileWriter(personelNumarasi, false);
        //Buffer veriler belleğe yazılmadan önce bir yerde toplanıp belleğe yazma işlemi ondan sonra yapılır.
        BufferedWriter buffer = new BufferedWriter(yazdir);
        buffer.write(kullaniciAdiTextBox.getText());
        buffer.close();

    }

    private void Log(boolean b, String personelNo) throws IOException {
        File log = new File("log.txt");
        if (log.exists()) {
            log.createNewFile();
        }
        FileWriter yazdir = new FileWriter(log, true);
        BufferedWriter buffer = new BufferedWriter(yazdir);
        if (b) {
            buffer.write("Başarılı Giriş" + " - [Personel : " + personelNo + " ] - [" + c.getTime() + "]" + "]\n");
        } else {
            buffer.write("Başarısız Giriş" + " - [Personel : " + personelNo + " ] - [" + c.getTime() + "]" + "]\n");
        }
        buffer.close();

    }
    Personel personel = new Personel();

    private void girisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButtonActionPerformed
        try {
            SqlBaglantisi baglanti = new SqlBaglantisi();
            baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());
            SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("select * from personel where personel_no='" + kullaniciAdiTextBox.getText() + "' and personel_sifre='" + sifreTextBox.getText() + "'");
            SqlBaglantisi.rs = SqlBaglantisi.prs.executeQuery();

            if (SqlBaglantisi.rs.next()) {
                Anasayfa anasayfa = new Anasayfa();
                anasayfa.setVisible(true);

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Yanlış veya Eksik Bilgi Girdiniz Lütfen Bilgileri Kontrol Ediniz !", "Bilgileri Kontrol Ediniz", HEIGHT);
            }

            while (SqlBaglantisi.rs.next()) {

                personel.setAdi(SqlBaglantisi.rs.getString("ad"));
                personel.setSoyadi(SqlBaglantisi.rs.getString("soyad"));
                personel.setPersonelNo(SqlBaglantisi.rs.getInt("personel_no"));

            }
            PersonelYazdir();
            Log(true, kullaniciAdiTextBox.getText());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Giriş Yapılamadı");
            try {
                Log(false, kullaniciAdiTextBox.getText());
            } catch (IOException ex) {
                Logger.getLogger(GirisEkranı.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_girisButtonActionPerformed

    private void sifreTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifreTextBoxKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            girisButton.requestFocus();
        }
        if (evt.getKeyChar() == KeyEvent.VK_SPACE || sifreTextBox.getText().length() == 25) {
            evt.consume();
        }
    }//GEN-LAST:event_sifreTextBoxKeyTyped

    private void kullaniciAdiTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kullaniciAdiTextBoxKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_SPACE || kullaniciAdiTextBox.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_kullaniciAdiTextBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kullaniciAdiTextBox;
    private javax.swing.JPasswordField sifreTextBox;
    // End of variables declaration//GEN-END:variables
}
