/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneotomasyonu.kitap;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kutuphaneotomasyonu.SqlBaglantisi;
import kutuphaneotomasyonu.siniflar.Yazar;
/**
 *
 * @author fxd
 */
public class YazarEkle extends javax.swing.JFrame {

    /**
     * Creates new form YazarEkle
     */
    public YazarEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ekleButton = new javax.swing.JButton();
        yazarSoyadiTextBox = new javax.swing.JTextField();
        yazarAdiTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        ekleButton.setText("Kaydet");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        yazarSoyadiTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yazarSoyadiTextBoxKeyTyped(evt);
            }
        });

        yazarAdiTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yazarAdiTextBoxKeyTyped(evt);
            }
        });

        jLabel1.setText("Yazar Ekle");

        jLabel2.setText("Ad");

        jLabel3.setText("Soyad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(yazarSoyadiTextBox)
                                .addComponent(yazarAdiTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ekleButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yazarAdiTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yazarSoyadiTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ekleButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed
        // TODO add your handling code here:
        try {

            SqlBaglantisi baglanti = new SqlBaglantisi();
            Yazar yazar = new Yazar();

            baglanti.Baglan(new SqlBaglantisi().getDbUrl(), new SqlBaglantisi().getdbKullanici(), new SqlBaglantisi().getdbSifre());

            SqlBaglantisi.prs = SqlBaglantisi.con.prepareStatement("insert into yazarlar(adi,soyadi) values(?,?)");

            yazar.setAd(yazarAdiTextBox.getText());
            SqlBaglantisi.prs.setString(1, yazar.getAd());

            yazar.setSoyad(yazarSoyadiTextBox.getText());
            SqlBaglantisi.prs.setString(2, yazar.getSoyad());

            SqlBaglantisi.prs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Yazar Başarıyla Eklendi", "Ekleme İşlemi Başarılı", ICONIFIED);
            yazarAdiTextBox.setText("");
            yazarSoyadiTextBox.setText("");
            KitapEkle.kategoriComboBox.removeAllItems();
            KitapEkle.yayineviComboBox.removeAllItems();
            KitapEkle.yazarComboBox.removeAllItems();
            KitapEkle.ComboBoxYukle();

            SqlBaglantisi.con.close();

        } catch (SQLException ex) {
            Logger.getLogger(KategoriEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ekleButtonActionPerformed

    private void yazarAdiTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yazarAdiTextBoxKeyTyped
        if (yazarAdiTextBox.getText().length() == 1)
            yazarAdiTextBox.setText(yazarAdiTextBox.getText().toUpperCase());

        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE || Character.isDigit(c) || yazarAdiTextBox.getText().length()==15)
            evt.consume();
    }//GEN-LAST:event_yazarAdiTextBoxKeyTyped

    private void yazarSoyadiTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yazarSoyadiTextBoxKeyTyped
        // TODO add your handling code here:
        if (yazarSoyadiTextBox.getText().length() == 1) 
            yazarSoyadiTextBox.setText(yazarSoyadiTextBox.getText().toUpperCase());
        
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE || Character.isDigit(c) || yazarSoyadiTextBox.getText().length()==15) 
            evt.consume();
    }//GEN-LAST:event_yazarSoyadiTextBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YazarEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YazarEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YazarEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YazarEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YazarEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField yazarAdiTextBox;
    private javax.swing.JTextField yazarSoyadiTextBox;
    // End of variables declaration//GEN-END:variables
}
